AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  crud_backend

  Sample SAM Template for crud_backend

Globals:
  Function:
    Timeout: 3

Resources:
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: LambdaBasicExecution
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: arn:aws:logs:*:*:*

  VehiclesApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Name: VehiclesApi
      Cors:
        AllowOrigin: "'*'"
        AllowHeaders: "'*'"
        AllowMethods: "'OPTIONS,POST,GET,PUT,DELETE'"

  GetDataVehicleFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: get_all_data_vehicle/
      Handler: app.lambda_handler
      Runtime: python3.12
      Policies:
        - AWSLambdaBasicExecutionRole
      Events:
        GetResource:
          Type: Api
          Properties:
            RestApiId: !Ref VehiclesApi
            Path: /get_all_data_vehicle
            Method: get

  InsertDataVehicleFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: insert_data_vehicle/
      Handler: app.lambda_handler
      Runtime: python3.12
      Policies:
        - AWSLambdaBasicExecutionRole
      Events:
        GetResource:
          Type: Api
          Properties:
            RestApiId: !Ref VehiclesApi
            Path: /insert_data_vehicle
            Method: post

  UpdateDataVehicleFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: update_data_vehicle/
      Handler: app.lambda_handler
      Runtime: python3.12
      Policies:
        - AWSLambdaBasicExecutionRole
      Events:
        GetResource:
          Type: Api
          Properties:
            RestApiId: !Ref VehiclesApi
            Path: /update_data_vehicle
            Method: put

  DeleteDataVehicleFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: delete_data_vehicle/
      Handler: app.lambda_handler
      Runtime: python3.12
      Policies:
        - AWSLambdaBasicExecutionRole
      Events:
        GetResource:
          Type: Api
          Properties:
            RestApiId: !Ref VehiclesApi
            Path: /delete_data_vehicle
            Method: delete

Outputs:
  GetVehicleApi:
    Description: "API Gateway endpoint URL with path get_all_data_vehicle for Prod stage to GetVehicle function"
    Value: !Sub "https://${VehiclesApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/get_all_data_vehicle/"
  InsertVehicleApi:
    Description: "API Gateway endpoint URL with path insert_data_vehicle for Prod stage to GetVehicle function"
    Value: !Sub "https://${VehiclesApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/insert_data_vehicle/"
  UpdateVehicleApi:
    Description: "API Gateway endpoint URL with path update_data_vehicle for Prod stage to GetVehicle function"
    Value: !Sub "https://${VehiclesApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/update_data_vehicle/"
  DeleteVehicleApi:
    Description: "API Gateway endpoint URL with path delete_data_vehicle for Prod stage to GetVehicle function"
    Value: !Sub "https://${VehiclesApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/delete_data_vehicle/"

  GetVehicleFunction:
    Description: "GetVehicleInfo Lambda Function ARN"
    Value: !GetAtt GetDataVehicleFunction.Arn
  InsertVehicleFunction:
    Description: "InsertVehicleInfo Lambda Function ARN"
    Value: !GetAtt InsertDataVehicleFunction.Arn
  UpdateVehicleFunction:
    Description: "UpdateVehicleInfo Lambda Function ARN"
    Value: !GetAtt UpdateDataVehicleFunction.Arn
  DeleteVehicleFunction:
    Description: "DeleteVehicleInfo Lambda Function ARN"
    Value: !GetAtt DeleteDataVehicleFunction.Arn

  LambdaExecutionRoleArn:
    Description: "Lambda Execution Role ARN"
    Value: !GetAtt LambdaExecutionRole.Arn

